bitfinexcom/bitfinex-api-node

examples/websockets-2.js
i noticed the latest code additions use a [standard](http://standardjs.com/) like coding style, so i've written the latest example in that style.
=> examples: add example for websocket v2 api

.travis.yml
=> use container based infra

test/local-rest-test.js, test/rest-test.js
the live api currently just returns 87 results, and not 100
=> Fix failing live test

rest.js, test/local-rest-test.js
=> rest1, http: support post_only

README.md
=> docs: mention auth event

rest.js
=> rest: add amount to claim_position payload

lib/maps.js, ws2.js
=> ws2: add candles

rest.js
Signed-off-by: Cameron Lockey <ctlockey@gmail.com>
=> Added support for /orders/hist in v1 rest

ws2.js
This helps applications know what symbol and resolution this data is for.
=> Expose key in message data

README.md, rest.js, rest2.js
this helps users to get first help for the nonce issue, avoiding
frustration and saving time
=> error: provide first help for nonce errors

examples/websockets-2-new-order.js
=> examples: add ws2 order example

examples/ws2/ticker.js, lib/transports/ws2.js
=> Fix ticker payload parsing & add example

examples/ws2/calc.js, examples/ws2/oco-order.js, examples/ws2/orders.js, lib/models/order.js, lib/transports/rest2.js, lib/transports/ws2.js, package.json, test/lib/transports/rest-2-issue-80-argument-length.js, test/lib/transports/ws2-unit.js
Needs https://github.com/bitfinexcom/bitfinex-api-node/pull/227
* stringifies `calc` command ws payload, closes #209 
* adds OCO example, closes #186 
* adds wrapper for RESTv1 methods within RESTv2
* adds `updateSettings`, `deleteSettings`, `getSettings` to `RESTv2`
* log statements/standard --fix/fixed tests
=> Fix various issues

README.md
Old PR, rebased. Originally https://github.com/bitfinexcom/bitfinex-api-node/pull/187
=> Fix README trades example

README.md
Closes https://github.com/bitfinexcom/bitfinex-api-node/issues/242
=> Add FAQ entries for order rate limits & lifecycle packets

lib/transports/ws2.js, test/lib/transports/ws2-unit.js
=> Fix: listener group filter failed on missing message data, closes #304

lib/model.js, test/lib/model.js
=> Fix: Model.unserialize() on objects

CHANGELOG, package.json
This release includes several bug fixes, refactorings, and new features. Check the changelog for a list :rocket: 
Moving forwards we will release new & smaller patches more often, as many of the fixes/features included in this release have already existed on `master` for some time now. For those users that reached out to us via Github issues after using an outdated copy of this library, I thank you for your patience :)
Changelog reproduced below:
- refactored general model handling (broke out field indexes) (c616696)
- REST API v1: add support for close position endpoint (14db6fe)
- REST API v2: added query param support to the candles() handler (be779c3)
- REST API v2: added platform status endpoint (5e3fe56)
- WS API v2: clean up channel subscriptions on open/close (7c17b96, 92ce89d)
- …
=> [WIP] Release 2.0.0-beta.1

examples/ws2/auth.js, examples/ws2/candles.js, examples/ws2/order_books.js, test/lib/transports/ws2-unit.js
=> (standard --fix)

lib/models/order.js, test/lib/models/order.js
See commit :shipit: adds some utility methods
=> Feature: Add helpers to get/set all order flags

examples/rest2/tickers.js
=> Fix: Rename 'Daily %' to 'Daily Change' in tickers table

README.md
IMO putting data in arrays doesn't make the calls that much faster.
=> (doc) Clarify reasoning of putting data in arrays

package.json
fixes:
```
Failed to parse file: /Users/robert/bitfinex/bitfinex-api-node/lib/models/order.js
Transformation error; return original code
{ Error: Line 455: Unexpected token *
at constructError (/Users/robert/bitfinex/bitfinex-api-node/node_modules/esprima/esprima.js:2407:21)
at createError (/Users/robert/bitfinex/bitfinex-api-node/node_modules/esprima/esprima.js:2426:17)
at unexpectedTokenError (/Users/robert/bitfinex/bitfinex-api-node/node_modules/esprima/esprima.js:2500:13)
at throwUnexpectedToken (/Users/robert/bitfinex/bitfinex-api-node/node_modules/esprima/esprima.js:2505:15)
```
and speeds up testing
=> test: remove code coverage

lib/transports/ws2.js, test/lib/transports/ws2-unit.js
=> Feature: Add support for DMS flag on auth

examples/rest2/ledgers.js, examples/rest2/movements.js, lib/transports/rest2.js, package.json
Placeholder PR, the example scripts need cli-table formatting.
=> Feature: Add RESTv2 Ledgers/Movements

lib/transports/ws2.js, test/lib/transports/ws2-unit.js
Verifies the connection is open & not closing before sending a message out on ws2
=> Improve ws2 send safety

index.js, lib/transports/rest2.js, test/lib/transports/rest-2-integration.js
Add option as to use bitfinex-api-node V2 with auth-token
=> add auth token option

lib/models/order_book.js, lib/transports/ws2.js, test/lib/transports/ws2-unit.js
Fixes errors resulting from price levels being removed from partially synced OBs; Fixes #371
=> Refactor/Fix: Support Removal of Unknown OB Price Levels

examples/ws2/notify_ui.js, lib/transports/ws2.js, test/lib/transports/ws2-unit.js
Wrapper around:
```js
this.send([0, 'n', null, {
type: UCM_NOTIFICATION_TYPE,
info: {
type,
message,
level,
image,
link,
sound
}
}])
```
=> Refactor Broadcast Notification Helper

lib/model.js, test/lib/model.js
Taken from https://github.com/bitfinexcom/bitfinex-api-node/pull/377, fixed tests to catch the bug
=> (fix) boolFields key in model unserialize

lib/transports/ws2.js, test/lib/transports/ws2-unit.js
=> (fix) skip auth seq # for error notifications w/ test

lib/transports/ws2.js, test/lib/transports/ws2-unit.js
=> Fix: 'trades' payload event name

lib/models/funding_info.js, lib/models/margin_info.js, test/lib/models/funding_info.js, test/lib/models/margin_info.js
=> Fix/Feature: Add FundingInfo model, fix MarginInfo model

CHANGELOG, lib/ws2_manager.js, package.json, test/lib/ws2_manager.js
```
2.0.0
- added CLI commands (971e8bf)
- added TradingTicker model (1099273)
- added model class transform support to RESTv2 (1099273)
- added ability to unserialize objects in Model.unserialize() (b23a576)
- added ledgers & movements examples (176d5a9)
- filled in FundingInfo model (268ecc9)
- updated MarginInfo model indices (268ecc9)
- increased max WSv2 listener limit to 1k (5ade818)
- REST API v2: fix calc balances API path (5e2f834)
- WS API v2: added notifyUI helper to generate broadcasts (22cb5bc)
- WS API v2: added support for DMS flag in auth (11e57b1)
- WS API v2: added socket manager for auto multiplexing (f693bb9)
- WS API v2: fixed error notification seq # tracking (1b1c1f3)
- WS API v2: fixed trades event name resolution w/ seq numbers (46af211)
- REST API v2: added …
```
=> Release: 2.0.0 Stable

lib/ws2_manager.js, test/lib/ws2_manager.js
Provides a way to mass-call methods on the underlying manager socket pool, closes https://github.com/bitfinexcom/bitfinex-api-node/issues/389
=> Feature: Add withAllSockets method to manager

lib/transports/rest2.js, lib/transports/ws2.js, test/lib/transports/ws2-unit.js
Closes https://github.com/bitfinexcom/bitfinex-api-node/issues/331
=> Feature: Automatic Re-Subscribe on Reconnect

doc/rest2.md, lib/models/currency.js, lib/models/index.js, lib/transports/rest2.js, test/lib/transports/rest-2-integration.js
New endpoint that gives the abbreviation and full name for each currency listed
=> [WYP] Currencie

lib/models/ledger_entry.js
Add from what wallet is the ledger entry
=> Add wallet to ledger_entry

lib/models/order_book.js, test/lib/models/order_book.js, test/lib/transports/ws2-unit.js
Adds funding support https://github.com/bitfinexcom/bitfinex-api-node/issues/409
=> Feature: Orderbook Funding Support

package.json
=> Feature: Release 2.0.1

doc/rest2.md
=> documentation

README.md, examples/ws2/trades.js
In this [commit](https://github.com/bitfinexcom/bitfinex-api-node/commit/755a40aef358362eb2eff4be3f6f5d276203399f) filter argument changed, but documents seems not update.
Now you have to pass filter object with key "symbol" when subscribeTrades with ws.
This PR just update the doc for new coming developers.
Thanks.
=> update doc for ws2 onTrades/onTradeEntry

package.json
bump version + add Ezequiel as contributor
=> bump version + add Ezequiel as contributor

package.json
=> Fix: Move babel deps to dev-deps

examples/ws2/funding_info.js
related API
https://docs.bitfinex.com/v2/reference#ws-auth-funding
https://docs.bitfinex.com/v2/reference#ws-input-calc
rest API example https://github.com/bitfinexcom/bitfinex-api-node/pull/447
=> new example to fetch funding info via ws API

.github/ISSUE_TEMPLATE, .github/PULL_REQUEST_TEMPLATE, .travis.yml
This pull request simply runs linting and unit tests on every commit. It also forces contributors to follow a template when opening new issues/PRs
=> Improve contribution pre-tests

CHANGELOG, docs/manager.md, docs/ws2.md, lib/transports/ws2.js, package.json
=> 3.0.2 Feature: Order Affiliate Codes

CHANGELOG, lib/ws2_manager.js, package.json
=> Feature: Add setAuthArgs() method to WS2Manager 4.0.3

CHANGELOG, package.json
=> (fix) mv several modules to deps from dev-deps for bfx-cli 4.0.13

CHANGELOG, README.md, package.json
=> Fix: README.md documentation reference 4.0.14

CHANGELOG, examples/util/debug_table.js, package.json
This PR fixes 2 high vulnerabilities which show `npm audit`
```console
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.17.11                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ bitfinex-api-node                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤ …
```
=> Fix 2 high vulnerabilities

CHANGELOG, examples/rest2/pulse.js, package.json
=> pulse examples added
