ws.js

This is a quick fix to parsing websocket trade events after the [recent websocket API update](http://blog.bitfinex.com/post/137764747714/websocket-api-update).

Update websocket trade format

---

examples/websockets.js

the latest version of the websocket wrapper does exposes the
`.ws` property _after_ the main constructor function is called.
note: did not use ES6 constants as I am not sure how you hande ES6 in your examples.

fix example

---

test/rest-2-smoke-test.js

simple test to verify the rest2 client works. will be used as a
base for pluggable data-transformers

test: add rest2 smoke test

---

index.js
test/ws-2-order-book.js
ws.js
ws2.js

changes to increase testability:
- make url injectable
- move creation of websocket connection out of constructor,
make it callable (e.g. after calling `close`)
Closes #38

orderbooks: add missing length parameter for WS

---

rest2.js
test/rest-2-issue-80-argument-length.js
test/rest-test.js

from #80
guard against invalid arguments length

	rest2: guard against invalid arguments length

---

rest.js

This might introduce pretty bad behaviors and security concerns in production. I believe this was for testing purposes and was not intended to stay there.

rest1: remove unsecure TLS config

---

rest.js

we have to pass a decimal string, e.g. `'1.01'`

claim-positions: fix parsing

---

rest2.js

As per the docs, it is `candles` not `stats1` Simple copy/paste error.

Wrong endpoint for candles

---

README.md

TypeError: ws.onTrade is not a function

Wrong method name in example

---

lib/transports/ws2.js

If we do not clean up the subscription refs on close we cannot subscribe again to previous subscribed symbols. So when you try to subscribe again those symbols are skipped because they are already present in `this._subscriptionRefs`.
If you try the code below you will receive data up to the first close. From then on no more data is received.
```javascript
const BFX = require('bitfinex-api-node');
const bfx = new BFX({
ws: {
autoReconnect: true,
}
});
const ws = bfx.ws(2);
ws.on('open', () => {
ws.subscribeTrades('tBTCUSD');
ws.on('trades', (symbol, trades) => {
console.log(symbol, trades);
});
});
ws.on('close', () => {
console.log('Connection closed!');
});
ws.open();
setInterval( () => {
// Simulate a socket close
ws._ws.close();
}, 5000);
```

(fix) Clean up subscriptors on closed connection

---

lib/transports/rest2.js
lib/transports/ws2.js
test/lib/transports/ws2-unit.js

* add query args field to REST2 `candles()` query
* allow duplicate candle/OB snapshots
* allow filtering `o*` event packets by all IDs & symbol

Improve Transport APIs

---

lib/transports/ws2.js

Mentioned in [#233](https://github.com/bitfinexcom/bitfinex-api-node/issues/233), candles are not resubscribing after reconnect because the subscriptionRefs object is not getting cleared. This fixes the issue so candle subscriptions resume assuming the user resubscribes on ws open.

Fix candle subscription on reconnect

---

examples/ws2/ob_checksum.js
lib/models/order_book.js
lib/transports/ws2.js
lib/util/precision.js
package.json
test/lib/models/order_book.js

Adds checksum logic to the `OrderBook` model for both raw & normal OBs, along with automatic verification of tracked OBs on `WSv2`. The implementation is based off of the description provided here: http://blog.bitfinex.com/api/bitfinex-api-order-books-checksums/
For reference, the price level structure:
* normal books (`P*`): `[price, count, amount]`
* raw books (`R0`): `[orderID, price, amount]`
1. setup `.env` file
2. run `node examples/ws2/ob_checksum.js`
3. wait for/spawn some OB updates and verify there are no errors in the output (the CS is logged)
While testing, keep in mind the fix for raw order book checksums is not yet on production :shipit:

Feature: OB Checksum Support & Validation

---

examples/ws2/atomic_order_update.js
lib/models/order.js
lib/transports/ws2.js
test/lib/models/order.js
test/lib/transports/ws2-integration.js

* WS2 client method: `WSv2.updateOrder(changes = {}) -> Promise`
* Order model method: `Order.update(changes = {}, ws = this._ws) -> Promise`
* an example
* tests!
The order update method applies the changes to the order, and then forwards them along to any registered ws2 (or the one provided). The promise is rejected if no ws2 client is available.
The ws2 client method in turn passes it out to the socket, and returns an event promise triggered by the next `ou-req` notification that has a matching ID.
This means we can now do this:
```js
const o = new Order({
cid: Date.now(),
symbol: 'tBTCUSD',
price: 1000,
amount: 0.02,
type: Order.type.EXCHANGE_LIMIT
}, ws)
// increase amount to 0.04 without cancelling the order
o.submit().then(() => {
o.update({ delta: '0.02' }).then(() => { …
```

Feature: Add atomic order update support, closes #271

---

lib/transports/ws2.js
test/lib/transports/ws2-unit.js

I also added in `isReconnecting()` & updated the flag internally, since it was unused before. Closes #291 
Previously, `_isOpen` would have been `true` if the `_onWSClose()` handler didn't have a chance to fire.

Fix: Ensure ws client is reset before re-connecting

---

lib/transports/ws2.js
test/lib/transports/ws2-unit.js

This commit is tiny, but closes #248 by checking the `platform.status` value on connection, and logging status updates.

Feature: Log server status when receiving info codes & on connect

---

examples/rest2/funding_credits.js
examples/rest2/funding_loans.js
examples/rest2/funding_offers.js
lib/models/funding_credit.js
lib/models/funding_loan.js
lib/models/funding_offer.js
test/lib/models/funding_credit.js
test/lib/models/funding_loan.js
test/lib/models/funding_offer.js
test/lib/transports/rest-2-integration.js

The indices for `FundingOffer`, `FundingLoan` and `FundingCredit` have been updated on the API side, this PR fixes the model field indices. The `'insure'` field has been removed.
I've included 3 minor examples that log funding offers/credit/loands to the console. Once #228 is merged in I will migrate them to the table format as well (another PR)
- #200

Fix: Funding model indices

---

examples/ws2/atomic_order_update.js
lib/models/order.js
lib/models/order_book.js
test/lib/models/order.js
test/lib/models/order_book.js

I tweaked the atomic order update example to showcase updates to partially filled orders. The example sells through the top bid in the OB, and then modifies the resulting order by increasing the price & the amount.
I've also added a few helper methods along with tests, and the order now emits an `update` event on close, and a `new` event after receiving a matching `on` packet. An `update` event is now emitted for all three listeners (new/update/close).
closes #300

Feature: Better atomic update example & new helpers

---

lib/models/order.js
test/lib/models/order.js

Previously you had to ensure the changeset price/amount fields were correctly formatted before submission; this now happens automatically.

Fix: Prepare/cast order update fields

---

lib/transports/rest2.js

Removes the '/r/' from '/auth/r/calc/order/avail', closes #292 
Needs https://github.com/bitfinexcom/bfx-api-mock-srv/pull/4 for tests to fail/pass with the change

Fix: Calc avail balance endpoint URL

---

examples/ws2/notify_ui.js
lib/transports/ws2.js
test/lib/transports/ws2-unit.js

Adds a `notifyUI(type, message)` method on the `WSv2` class, which sends a broadcast notification out which can be detected by any open `bitfinex.com` UI client, triggering a desktop notification. In the future, the mobile apps will also support the creation of push notifications in response to incoming broadcast notifications.

Feature: Add notifyUI() Helper for WSv2

---

examples/rest2/ledgers.js
examples/rest2/movements.js
lib/models/index.js
lib/models/ledger_entry.js
lib/models/movement.js
lib/transports/rest2.js
test/lib/models/ledger_entry.js
test/lib/models/movement.js

This PR adds `start`/`end`/`limit` query arg support to the `ledgers()` and `movements()` RESTv2 endpoints. The defaults are an end of `Date.now()` and a limit of `25`.
I've also included the models for ledger entries & movements, courtesy of ezequiel :dancer:.

Feature: Paginate Ledgers/Movements RESTv2

---

README.md

when i added it in 2017 it was meant to credit and honor
co-authors. sadly this is the first open source project where
people regularly misuse the credit section to spam authors via
email about their very own personal support requests.

docs: remove contributor section

---

lib/models/order_book.js
test/lib/models/order_book.js

pass down `raw` option to fix orderID vs. count property in
resulting entry

orderbooks: unserialize fix for raw books

---

examples/bfx.js
examples/ws2_manager.js
lib/transports/rest2.js
lib/transports/ws2.js
lib/ws2_manager.js
test/lib/ws2_manager.js

Closes #369 
Adds a `WS2Manager` class which wraps `WSv2`, automatically opening new socket connections when a `subscribe()` call would exceed the new limit of 50 data channels per connection.
The new manager should be used when subscribing to `'trades'`, `'candles'`, `'ticker'`, or `'book'` channels. Otherwise, call `getSocket(i)` to access an underlying socket `WSv2` class instance.
A few high level helpers are provided on `WS2Manager` for requesting sockets suitable for `subscribe()` calls:
* `getFreeDataSocket()`
* `getSocketWithDataChannel()`
* `getSocketWithChannel()`
The manager takes `(socketArgs, authArgs)` params which are shared between all internal sockets; if authentication credentials are provided to the constructor, or later supplied via a call to `.auth({ ... })`, all …

Feature: Socket Manager for Auto Multiplexing

---

examples/ws2/trades.js
lib/transports/ws2.js
test/lib/transports/ws2-integration.js
test/lib/transports/ws2-unit.js

This PR refactors the internal trades listeners to split up public & account trades. Public `tu` events are mapped to the `onTrades()` listener along with the initial trades snapshot, being isomorphic with the other listeners (snapshot + updates). Account trades are split between `onAccountTradeEntry` and `onAccountTradeUpdate`, since there is no snapshot.
In reference to https://github.com/bitfinexcom/bitfinex-api-node/pull/388
```
const ws = bfx.ws(2)
ws.on('open', () => {
debug('open')
ws.subscribeTrades('tEOSUSD')
ws.auth()
})
ws.onTradeEntry({ pair: 'EOSUSD' }, (trade) => {
debug('te: %j', trade)
})
ws.onTrades({ pair: 'EOSUSD' }, (trades) => {
debug('trades: %j', trades)
})
ws.onAccountTradeEntry({ symbol: 'tEOSUSD' }, (trade) => {
debug('account te: %j', trade)
}) …
```

Refactor: Split up trades listeners between public & private trades

---

lib/transports/ws2.js

'pong' events are ignored in current ws2 implementation. 
Since the API update limiting a connection to 50 channels, one may experience no activity whatsoever for more than 10-15 seconds on a connection with illiquid coins.
Emitting a pong event back to the client allows one to make sure the connection is still up.

[ws2] add 'pong' event handler

---

lib/transports/ws2.js
lib/ws2_manager.js

Closes #414 
Tweaks things to handle promises returned by `open()`, `close()` and `auth()` in various places, in order to avoid errors bubbling up.

Fix: Unhandled Promises

---

lib/transports/ws2.js
test/lib/transports/ws2-unit.js

I found a few problems with the reconnect behavior.
The original code:
``` 
async reconnect () {
if (!this._ws) {
return this.open()   <-- this leads to reconnected, but unauthorized websockets, I removed that part
}
this._isReconnecting = true
await this.close()   <-- this.close is calling reconnect() a second time in _onWSClose() which leads to promise rejections in different places.
await this.open() <-- the promise rejection in open() was triggered in some edge cases because of multiple calls of reconnect()
if (this._wasEverAuthenticated) {
await this.auth()
}
}
```
I splitted the operation into two parts:
```
async reconnect () {
this._isReconnecting = true
if (this._ws !== null && this._isOpen) {  // did we get a watchdog timeout and need to close the connection?
await this.close() …
```

Improved reconnect

---

examples/rest2/funding_info.js

add the fundingInfo example. 
https://docs.bitfinex.com/v2/reference#rest-auth-info-funding
I found the DURATION_LEND is updated correctly but the YIELD_LEND is not updated

new example to fetch funding info

---

examples/ws2/order_books.js

I haven't tested the script, but it looks like lastMidPrice will always be set to -1. Added L36 to set lastMidPrice to the current midPrice value so the if statement won't return TRUE on every order book update.

set lastMidPrice value

---

CHANGELOG
lib/transports/ws2.js
package.json
test/lib/transports/ws2-unit.js

Notification sequence numbers no longer advance (deploy to production pending in the next 3 weeks), this PR removes them from consideration in the sequence audit logic.
Closes #423

v2.0.10 Fix: Ignore Notification Auth Seq Numbers

---

CHANGELOG
examples/rest2/positions.js
examples/rest2/submit_funding_offer.js
examples/rest2/submit_order.js
examples/rest2/wallet.js
examples/ws2/candles.js
package.json
test/lib/transports/ws2-unit.js

Adds new V2 endpoints to the lib:
```
`/v2/auth/w/order/submit` (same data used in sending orders through WS, `on`)
`/v2/auth/w/order/update`  (same data used in sending orders through WS, `ou`)
`/v2/auth/w/order/cancel` (same data used in sending orders through WS, `oc`)
`/v2/auth/w/order/multi`  (same data used in sending orders through WS `ox_multi`, but inside an array called `ops`, ie. `{"ops": [["on", {"symbol": "tBTCUSD", "amount": "5", "type": "LIMIT", "price": "10"}]]}`)
`/v2/auth/w/order/cancel/multi` (same data used in sending orders through WS, `oc`)
`/v2/auth/w/position/claim` (params: `id`)
`/v2/auth/w/funding/offer/submit` (same data used in sending orders through WS, `on`)
`/v2/auth/w/funding/offer/cancel` (same data used in sending orders through WS, `on`) …
```

Integrate v2 endpoints

---

lib/ws2_manager.js

Added freq attribute to filters inside order book subscription in ws2 manager (see [docs](https://docs.bitfinex.com/reference#ws-public-order-books) for missing param)
- N/A
- N/A
- Added support for missing optional param inside subscribe to order books channel

freq added to order book filter in ws2 manager

---

CHANGELOG
package.json

A API breaking fix was added to bfx-api-node-rest and this pull request adds it.
Please see https://github.com/bitfinexcom/bfx-api-node-rest/pull/42

bump package to 4.0.0 and include node-rest hotfix

---

CHANGELOG
examples/ws2/trades.js
lib/transports/ws2.js
package.json
test/lib/transports/ws2-unit.js

Properly route `fte`/`ftu` messages to their respective handlers, closes #456

Fix: Funding trade event routing 3.0.3

---

CHANGELOG
lib/ws2_manager.js
package.json

Adds a `reconnect()` method to the WSv2 Manager class, which calls `reconnect()` on all sockets.

Add reconnect() method to ws2 manager 4.0.2

---

CHANGELOG
docs/ws2.md
examples/ws2/ob_checksum.js
lib/transports/ws2.js
package.json
test/lib/transports/ws2-unit.js

This pull request maintains a lossless string copy of the orderbook for use when generating the checksum string to avoid any nasty floating point precision errors.
- None
- https://github.com/bitfinexcom/bfx-api-node-models/pull/33

Generate checksum using strings

---

CHANGELOG
lib/transports/ws2.js
lib/ws2_manager.js
package.json
test/lib/transports/ws2-unit.js
test/lib/ws2_manager.js

Adds `updateAuthArgs()` and `getAuthArgs()`, along with an internal `_authArgs` map. The map is used within `auth()` to provide `calc` and `dms` defaults.

Feature: Auth Arg Management 4.0.5

---

CHANGELOG
lib/transports/ws2.js
package.json
test/lib/transports/ws2-unit.js

Previously the internal `_enabledFlags` value was not being correctly updated based on the state of `seqAudit` in the constructor or subsequent changes.
This fixes it + associated tests, closes #521

Fix: Flag Persistence 4.0.6

---

CHANGELOG
lib/transports/ws2.js
package.json
test/lib/transports/ws2-integration.js
test/lib/transports/ws2-unit.js

Updates a few methods in WSv2 and several tests to use async/await instead of waiting for the `open` or `auth` events. Quality of life improvement, makes the tests far easier to follow.
Needs to be merged after/will have minor conflicts with https://github.com/bitfinexcom/bitfinex-api-node/pull/522 (4.0.6)

Refactor: Use async/await where possible in tests/ws2 4.0.7

---

CHANGELOG
lib/ws2_manager.js
package.json

`WS2Manager` was overwriting internal auth args on each call to `auth()`, which provided default `dms` and `calc` params.

Fix: Respect internal auth arg settings in WS2Manager 4.0.9

---

.gitignore
CHANGELOG
README.md
examples/rest2/order-history.js
examples/rest2/trade-history.js
examples/ws2/notifications.js
index.js
lib/transports/ws2.js
package.json
test/lib/transports/ws2-integration.js
test/lib/transports/ws2-unit.js

Needs https://github.com/bitfinexcom/bfx-api-mock-srv/pull/29

Fix: Concurrent tests 4.0.10

---

CHANGELOG
package.json

Moves `readline-promise` to deps from dev-deps for `bfx-cli` (normally it's a dev dep for this repo, but bfx-cli utilizes the examples).
Also bumps `bfx-api-node-rest` and `bfx-api-node-models` for travis.

Fix: Move readline-promise to deps from dev-deps 4.0.12

---

lib/transports/ws2.js
package.json
test/lib/transports/channels.js
test/lib/transports/ws2-unit.js

`Object.keys` casts to strings, channel ids can be are
numbers, the compare function does not cast.
in general its faster to do a direct object access instead of
converting to an array and doing a search on the array.

fix: unsubscribe fails depending on channel id type

---

lib/transports/ws2.js
lib/ws2_manager.js
test/index.js
test/lib/transports/ws2-unit.js
test/lib/ws2_manager.js

The problem is that while saving the creds in Settings, the API key and secret were not dynamically changed in WS2. When reconnecting, it still used the old ones. 
Depends on: https://github.com/bitfinexcom/bfx-api-mock-srv/pull/48
- Fix ignored authArgs on reconnect
https://user-images.githubusercontent.com/70510980/115753939-62a6e180-a3a4-11eb-8517-df1ae0b9e258.mov

Fix reconnect
